### PR TITLE
Add moar commands!!

### PR DESCRIPTION
**Pull request by Bottersnike**
I just added a ton of commands because why not?
Commands:

- `hash`/`md5` Hash a string using MD5
- `sha1` Hash a string using SHA1
- `sha256` Hash a string using SHA256
- `sha512` Hash a string using SHA512
- `g`/`google` Google search
- `wolfram`/`wa`/`alpha`/`wolfram_alpha` Do a search on wolfram alpha (returns the url)
- `mods`/`moderators`/`listmods`/`list_mods`/`list_moderators` Get a list of all the online, idle and offline moderators on the server (respects invis and treats dnd as offline).

(So what if some of them have loads of aliases.. It makes it easier for the end user.)

### CODE REVIEW

**Review by qixils — CHANGES_REQUESTED** [review]
`help` command wasn't updated and my hosting environment breaks the `mods` command. Why? I don't friccin know. Besides that, everything works fine.

**Comment by Bottersnike** [comment]
`help` I can work on.
I think that for `mods`, the bot needs to poll Discord for every user's status manually. I'm looking into it RN.

**Comment by qixils** [comment]
merging #4 soon:tm: which is not compatible with this PR

**Comment by qixils** [comment]
#4 (or, future pull request to fix branch) doesn't affect this

**Review by qixils — APPROVED** [review]

**Comment by Bottersnike** [comment]
I'll work on trying to get these all into the python port soon. ETA 1-2 days.

**Pull request merged**
